"""Seed initial pattern_templates as defined in section 14 of the spec."""
from __future__ import annotations

from decimal import Decimal
from typing import List

from backend.app.core.logging import logger
from backend.db import models
from backend.db.session import SessionLocal


SEED_PATTERNS: List[dict] = [
    {
        "pattern_id": "UNQ-H-0001",
        "name": "Most Barrels Last 50 PA",
        "description_template": "{{player_name}} has the most barrels in MLB over his last 50 PA ({{metric_value}} barrels).",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "A_BARRELS",
        "filters_json": {"conditions": [{"field": "is_barrel", "op": "=", "value": True}]},
        "order_direction": "desc",
        "metric": "count_barrels",
        "target_sample": 50,
        "min_sample": 10,
        "unicorn_weight": Decimal("1.2"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-H-0002",
        "name": "Highest Hard-Hit Rate Last 50 PA",
        "description_template": "{{player_name}} leads MLB in hard-hit rate over his last 50 PA.",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "A_BARRELS",
        "filters_json": {"conditions": []},
        "order_direction": "desc",
        "metric": "hard_hit_rate",
        "target_sample": 50,
        "min_sample": 10,
        "unicorn_weight": Decimal("1.2"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-H-0003",
        "name": "Highest xwOBA Last 50 PA",
        "description_template": "{{player_name}} tops MLB in xwOBA over his last 50 PA.",
        "entity_type": "batter",
        "base_table": "pa_facts",
        "category": "A_BARRELS",
        "filters_json": {"conditions": []},
        "order_direction": "desc",
        "metric": "xwoba_avg",
        "target_sample": 50,
        "min_sample": 10,
        "unicorn_weight": Decimal("1.2"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-H-0004",
        "name": "Lowest Chase % Last 50 PA",
        "description_template": "{{player_name}} owns the lowest chase rate over his last 50 PA.",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "A_BARRELS",
        "filters_json": {"conditions": []},
        "order_direction": "asc",
        "metric": "chase_rate",
        "target_sample": 50,
        "min_sample": 10,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.0"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-H-0005",
        "name": "Highest Contact % Last 50 PA",
        "description_template": "{{player_name}} leads MLB in contact rate over his last 50 PA.",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "A_BARRELS",
        "filters_json": {"conditions": []},
        "order_direction": "desc",
        "metric": "contact_rate",
        "target_sample": 50,
        "min_sample": 10,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.0"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-H-0010",
        "name": "Most Opposite-Field HR (Season-To-Date)",
        "description_template": "{{player_name}} has the most oppo-field HR this season.",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "B_DIRECTION",
        "filters_json": {"conditions": [
            {"field": "is_hr", "op": "=", "value": True},
            {"field": "hit_direction", "op": "=", "value": "oppo"}
        ]},
        "order_direction": "desc",
        "metric": "count_hr",
        "target_sample": 0,
        "min_sample": 1,
        "unicorn_weight": Decimal("1.2"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-H-0011",
        "name": "Most Pulled HR (Season-To-Date)",
        "description_template": "{{player_name}} has the most pulled HR this season.",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "B_DIRECTION",
        "filters_json": {"conditions": [
            {"field": "is_hr", "op": "=", "value": True},
            {"field": "hit_direction", "op": "=", "value": "pull"}
        ]},
        "order_direction": "desc",
        "metric": "count_hr",
        "target_sample": 0,
        "min_sample": 1,
        "unicorn_weight": Decimal("1.2"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-H-0012",
        "name": "Most 100+ EV Oppo Hits on Low-Away Sliders",
        "description_template": "{{player_name}} has the most 100+ EV opposite-field hits on low-away sliders.",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "B_DIRECTION",
        "filters_json": {"conditions": [
            {"field": "launch_speed", "op": ">=", "value": 100},
            {"field": "hit_direction", "op": "=", "value": "oppo"},
            {"field": "loc_region", "op": "=", "value": "low_away"},
            {"field": "pitch_type", "op": "=", "value": "SL"}
        ]},
        "order_direction": "desc",
        "metric": "count_hr",
        "metric_expr": "COUNT(*)",
        "target_sample": 0,
        "min_sample": 1,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.0"),
        "complexity_score": 4,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-H-0020",
        "name": "Most HR in 3-0 Counts",
        "description_template": "{{player_name}} leads MLB in HR hit in 3-0 counts.",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "COUNT",
        "filters_json": {"conditions": [
            {"field": "is_hr", "op": "=", "value": True},
            {"field": "count_str", "op": "=", "value": "3-0"}
        ]},
        "order_direction": "desc",
        "metric": "count_hr",
        "target_sample": 0,
        "min_sample": 1,
        "unicorn_weight": Decimal("1.2"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 2,
        "requires_count": True,
        "count_value": "3-0",
    },
    {
        "pattern_id": "UNQ-H-0021",
        "name": "Highest xwOBA in 3-2 Counts",
        "description_template": "{{player_name}} has the best xwOBA in MLB in 3-2 counts.",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "COUNT",
        "filters_json": {"conditions": [
            {"field": "count_str", "op": "=", "value": "3-2"}
        ]},
        "order_direction": "desc",
        "metric": "xwoba_avg",
        "metric_expr": "AVG((SELECT p.xwoba FROM pa_facts p WHERE p.pa_id = pitch_facts.pa_id))",
        "target_sample": 0,
        "min_sample": 5,
        "unicorn_weight": Decimal("1.2"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": True,
        "count_value": "3-2",
    },
    {
        "pattern_id": "UNQ-P-0100",
        "name": "Lowest xwOBA Allowed Over Last 3 Starts",
        "description_template": "{{player_name}} has the lowest xwOBA allowed over his last 3 starts.",
        "entity_type": "pitcher",
        "base_table": "pa_facts",
        "category": "STARTER",
        "filters_json": {"conditions": []},
        "order_direction": "asc",
        "metric": "xwoba_avg",
        "target_sample": 60,
        "min_sample": 20,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-P-0101",
        "name": "Highest Whiff % Over Last 3 Starts",
        "description_template": "{{player_name}} has the highest whiff rate over his last 3 starts.",
        "entity_type": "pitcher",
        "base_table": "pitch_facts",
        "category": "STARTER",
        "filters_json": {"conditions": []},
        "order_direction": "desc",
        "metric": "whiff_rate",
        "target_sample": 60,
        "min_sample": 20,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-P-0102",
        "name": "Lowest Hard-Hit % Allowed Over Last 3 Starts",
        "description_template": "{{player_name}} allows the lowest hard-hit rate over his last 3 starts.",
        "entity_type": "pitcher",
        "base_table": "pitch_facts",
        "category": "STARTER",
        "filters_json": {"conditions": []},
        "order_direction": "asc",
        "metric": "hard_hit_rate",
        "target_sample": 60,
        "min_sample": 20,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-P-0103",
        "name": "Most Strikeouts Over Last 3 Starts",
        "description_template": "{{player_name}} has the most strikeouts over his last 3 starts.",
        "entity_type": "pitcher",
        "base_table": "pa_facts",
        "category": "STARTER",
        "filters_json": {"conditions": []},
        "order_direction": "desc",
        "metric": "total_k_last_3_starts",
        "metric_expr": "SUM(CASE WHEN result = 'K' THEN 1 ELSE 0 END)",
        "target_sample": 60,
        "min_sample": 20,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-R-0200",
        "name": "Lowest xwOBA Allowed Over Last 5 Relief Appearances",
        "description_template": "{{player_name}} has the lowest xwOBA allowed over his last 5 relief outings.",
        "entity_type": "pitcher",
        "base_table": "pa_facts",
        "category": "RELIEVER",
        "filters_json": {"conditions": []},
        "order_direction": "asc",
        "metric": "xwoba_avg",
        "target_sample": 40,
        "min_sample": 10,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.0"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-R-0201",
        "name": "Highest Whiff % Over Last 5 Relief Appearances",
        "description_template": "{{player_name}} has the highest whiff rate over his last 5 relief outings.",
        "entity_type": "pitcher",
        "base_table": "pitch_facts",
        "category": "RELIEVER",
        "filters_json": {"conditions": []},
        "order_direction": "desc",
        "metric": "whiff_rate",
        "target_sample": 40,
        "min_sample": 10,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.0"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-R-0202",
        "name": "Lowest Hard-Hit % Allowed Over Last 5 Relief Appearances",
        "description_template": "{{player_name}} allows the lowest hard-hit rate over his last 5 relief outings.",
        "entity_type": "pitcher",
        "base_table": "pitch_facts",
        "category": "RELIEVER",
        "filters_json": {"conditions": []},
        "order_direction": "asc",
        "metric": "hard_hit_rate",
        "target_sample": 40,
        "min_sample": 10,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.0"),
        "complexity_score": 1,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-P-0300",
        "name": "Most HR Allowed After 75+ Pitches",
        "description_template": "{{player_name}} has allowed the most HR after reaching 75 pitches.",
        "entity_type": "pitcher",
        "base_table": "pitch_facts",
        "category": "FATIGUE",
        "filters_json": {"conditions": [
            {"field": "is_hr", "op": "=", "value": True},
            {"field": "pitch_number_game", "op": ">=", "value": 75}
        ]},
        "order_direction": "desc",
        "metric": "count_hr",
        "target_sample": 0,
        "min_sample": 1,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 2,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-P-0301",
        "name": "Lowest xwOBA Allowed After 70+ Pitches",
        "description_template": "{{player_name}} owns the lowest contact quality after 70 pitches.",
        "entity_type": "pitcher",
        "base_table": "pitch_facts",
        "category": "FATIGUE",
        "filters_json": {"conditions": [
            {"field": "pitch_number_game", "op": ">=", "value": 70}
        ]},
        "order_direction": "asc",
        "metric": "xwoba_avg",
        "metric_expr": "AVG((SELECT p.xwoba FROM pa_facts p WHERE p.pa_id = pitch_facts.pa_id))",
        "target_sample": 0,
        "min_sample": 10,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 2,
        "requires_count": False,
        "count_value": None,
    },
    {
        "pattern_id": "UNQ-H-0400",
        "name": "Most HR in Coors Field",
        "description_template": "{{player_name}} has the most HR in Coors Field this season.",
        "entity_type": "batter",
        "base_table": "pitch_facts",
        "category": "PARK",
        "filters_json": {"conditions": [
            {"field": "games.venue_id", "op": "=", "value": 1},
            {"field": "is_hr", "op": "=", "value": True}
        ]},
        "order_direction": "desc",
        "metric": "count_hr",
        "target_sample": 0,
        "min_sample": 1,
        "unicorn_weight": Decimal("1.0"),
        "public_weight": Decimal("1.2"),
        "complexity_score": 2,
        "requires_count": False,
        "count_value": None,
    },
]


def seed() -> None:
    with SessionLocal() as session:
        for data in SEED_PATTERNS:
            existing = session.get(models.PatternTemplate, data["pattern_id"])
            if existing:
                for key, value in data.items():
                    setattr(existing, key, value)
            else:
                session.add(models.PatternTemplate(**data))
        session.commit()
    logger.info("Seeded %s patterns", len(SEED_PATTERNS))


if __name__ == "__main__":
    seed()
